import express from "express";
import { getUser } from "../controllers/users/getUser.js";
import { deleteUser } from "../controllers/users/deleteUser.js";
import { putUser } from "../controllers/users/PutUser.js";
import { createUser} from "../controllers/users/createUser.js";
import { authMiddleware } from "../middleware/authMiddleware.js";
const router = express.Router();
router.get("/:id", authMiddleware, getUser);
router.delete("/delete/:id", authMiddleware, deleteUser);
router.put("/", putUser);
router.post("/create", createUser);
export default router;
