import express from "express";
import { getUsers } from "../resolvers/users/getUsers.js";
import { deleteUsers } from "../resolvers/users/deleteUsers.js";
import { putUsers } from "../resolvers/users/PutUsers.js";
import { createUser} from "../resolvers/users/createUser.js";
import { authMiddleware } from "../middleware/authMiddleware.js";
export const router = express.Router();
router.get("/", authMiddleware, getUsers);
router.delete("/", deleteUsers);
router.put("/", putUsers);
router.post("/users", createUser);
router.post("/", createUser);
export default router;
