import express from "express";
import { getUser } from "../controllers/users/getUser.js";
import { deleteUser } from "../controllers/users/deleteUser.js";
import { putUser } from "../controllers/users/PutUser.js";
import { createUser} from "../controllers/users/createUser.js";
import { authMiddleware } from "../middleware/authMiddleware.js";
export const router = express.Router();
router.get("/", authMiddleware, getUser);
router.delete("/", deleteUser);
router.put("/", putUser);
router.post("/users", createUser);
router.post("/", createUser);
export default router;
